### PR TITLE
Initial Lua scripting support

### PR DESCRIPTION
**Pull request by Wizzard033**
I still have a bit more to do feature-wise, but this is already usable

### CODE REVIEW

**Comment by Wizzard033** [comment]
Here's a simple rundown on how to use it:

<?lua chunk ?>
Processes the Lua chunk execution results. The alternative form <% chunk %> can also be used.

<?lua= expression ?>
Processes the Lua expression and outputs its results into the HTML file. The alternative form <%= expression %> can also be used.

The included "index.htm" file shows this off.

**Comment by Wizzard033** [comment]
This is now done

**Comment by Wizzard033** [comment]
Here's an example of some interesting syntax that I enabled
```
<ul>
    <% for i, item in ipairs(list) do %>
    <li><%= item %></li>
    <% end %>
</ul>
```
This intermixes Lua and HTML where a loop is recursively including HTML

**Comment by alfredlucero** [comment]
I like how you can do a similar ng-repeat in AngularJS with your Lua and HTML to loop through items and add tags based on that. Great work dude! I looked through the SQLite and Lua set-up files briefly and the unit tests look good and in line with style. Cannot wait to see it demoed in class. 👍

**Comment by alfredlucero** [comment]
Tests passed woo! Seems like Makefile has issues with ordering the LDFLAGS. When Jordan adds his feature he will take note of that as well or else it won't build. Also, our deploy folder can use some re-organizing to cut out some unnecessary files. Jordan's latest changes will also fix the proxy bunny integration test issue as well.

**Comment by Wizzard033** [comment]
This is ready to merge once again

**Pull request merged**
